import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Theme } from "./theme";
import SessionWatcher from '@/components/session/SessionWatcher';
import { cn } from "@/lib/utils";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Theme></Theme>
      <body className={cn("h-screen",
        geistSans.variable,
        geistMono.variable,
        "antialiased bg-linear-to-br from-background to-accent/40"
      )}
      >
        <SessionWatcher />
        {children}
      </body>
    </html>
  );
}
