name: Validate Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Validate commits
        run: |
          echo "Validando mensagens de commit..."
          git log origin/main..HEAD --pretty=format:"%s" | while read msg; do
            if ! echo "$msg" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|chore|build|ci|revert)(\(.+\))?!?:"; then
              echo "❌ Commit inválido: $msg"
              echo "Use Conventional Commits: feat|fix|docs|style|refactor|perf|test|chore|build|ci|revert"
              exit 1
            fi
          done
          echo "✅ Todos os commits são válidos!"
